medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      # host: postgres 
      host : localhost     
      user: medical_user
      password: secure_password_123
      port: 5432
      dbname: medical_warehouse
      schema: raw
      threads: 4
