medical_warehouse:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "127.0.0.1"
      user: "medical_user"
      password: "secure_password_123"
      port: 5432
      dbname: "medical_warehouse"
      schema: public
      threads: 4
